// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqwekuzmqguikbsyqhrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxd2VrdXptcWd1aWtic3lxaHJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMzE1MDEsImV4cCI6MjA2MzcwNzUwMX0.w4lHQwnvqORbT_24RsrOYYMx4s3P1gV-GECpVW3ArwU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);